NUMPY : numerical python . Works excatly like python list.Works 5x faster than list. Developed by Travis 

In [1]:
import numpy as np

In [6]:
arr=np.array([1,2,3])
print(arr.ndim)
print(arr)

1
[1 2 3]


In [9]:
arr1=np.array([[1,2,3],[4,5,6]])
print(arr1)
print(arr1.ndim)

[[1 2 3]
 [4 5 6]]
2


**Slicing**

In [ ]:
arr3=np.array([2,5,1,7,11,44,56,88,35,78])
print(arr3[2:8])
print(arr3[1:])
print(arr3[3:6:2])  #start,end,two steps
print(arr3[::2])  #start,end and two steps 
print(arr3[::-1])  #reverse
print(arr3[::-2]) #reverse and two steps

[ 1  7 11 44 56 88]
[ 5  1  7 11 44 56 88 35 78]
[ 7 44]
[ 2  1 11 56 35]
[78 35 88 56 44 11  7  1  5  2]
[78 88 44  7  5]


**Statistical operations**

In [ ]:
arr4=np.array([2,5,1,7,11,44,56,88,35,78])
np.max(arr4)  #maximum defualt in int value
np.min(arr4)  #minimum in int value
np.sum(arr4)  #sum in int value
np.mean(arr4)  #average in float value
np.median(arr4)  #middle value in float value

np.float64(23.0)

**Mathematical operatiosns**

In [7]:
arr5=np.array([1,2,3,4])
arr6=np.array([5,6,7,8])

In [8]:
np.add(arr5,arr6)

array([ 6,  8, 10, 12])

In [9]:
np.subtract(arr5,arr6)

array([-4, -4, -4, -4])

In [10]:
np.multiply(arr5,arr6)

array([ 5, 12, 21, 32])

In [11]:
np.divide(arr5,arr6)

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

**Random numbers**

In [2]:

x=np.random.rand()
print(x)

0.6753548438888298


In [3]:
y=np.random.rand(3)
print(y)

[0.7294196  0.54197918 0.03157422]


In [4]:
z=np.random.randint(1,10)
print(z)

8


In [5]:
s=np.random.randint(1000,9999)
print(s)

3451


In [6]:
a=np.random.randint(100000,9999999)
print(a)

9686633


In [7]:
t=np.random.randn()
print(t)

-1.246920764570309


**Reshaping**

In [8]:
b=np.array([3,5,1,8,0,6])
new=b.reshape(3,2)
print(new)

[[3 5]
 [1 8]
 [0 6]]


**Raise power**

In [ ]:
s1=np.array([9,8,7,6,1])
np.power(s1,2) 

array([81, 64, 49, 36,  1])

In [4]:
np.power(s1,3)

array([729, 512, 343, 216,   1])

**Square root**

In [6]:
np.sqrt(s1)

array([3.        , 2.82842712, 2.64575131, 2.44948974, 1.        ])